# Generated by Django 2.1 on 2018-09-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('dia_inicio', models.CharField(max_length=15)),
                ('mes_inicio', models.CharField(max_length=15)),
                ('finalizado', models.BooleanField(default=False)),
                ('dia_semana', models.CharField(max_length=10)),
                ('comentario', models.ManyToManyField(to='comentarios.Comentario')),
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugar')),
            ],
        ),
    ]
