# Generated by Django 2.1 on 2018-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='dia_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_hora_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='mes_inicio',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugar'),
        ),
    ]
