# Generated by Django 2.1 on 2018-10-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20181002_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='comentario',
            field=models.ManyToManyField(blank=True, to='comentarios.Comentario'),
        ),
    ]
