# Generated by Django 2.1 on 2018-09-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('usuario', models.ManyToManyField(to='usuarios.Usuario')),
            ],
        ),
    ]
