# Generated by Django 2.1 on 2019-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='valor',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
