# Generated by Django 2.1 on 2018-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_uid'),
        ('lugares', '0001_initial'),
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='lugar',
        ),
        migrations.AddField(
            model_name='visita',
            name='lugar',
            field=models.ManyToManyField(to='lugares.Lugar'),
        ),
        migrations.RemoveField(
            model_name='visita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='visita',
            name='usuario',
            field=models.ManyToManyField(to='usuarios.Usuario'),
        ),
    ]
