# Generated by Django 2.1 on 2018-12-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
