# Generated by Django 2.1 on 2018-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181202_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(default='Por definir', max_length=15),
            preserve_default=False,
        ),
    ]
