# Generated by Django 2.1 on 2018-12-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('municipios', '0001_initial'),
        ('usuarios', '0004_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(default=76, on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio'),
        ),
    ]
