# Generated by Django 2.1 on 2019-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='Alguna descripcion', max_length=200),
            preserve_default=False,
        ),
    ]
