# Generated by Django 2.1 on 2018-09-21 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('tags', '0001_initial'),
        ('categorias', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=None), size=None)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('sitio_web', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('telefono', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=None), size=None)),
                ('redes', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None), size=None)),
                ('direccion', models.CharField(max_length=100)),
                ('hora_abierto', models.TimeField()),
                ('hora_cerrado', models.TimeField()),
                ('dias_servicio', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('municipio', models.CharField(max_length=100)),
                ('categoria', models.ManyToManyField(to='categorias.Categoria')),
                ('comentario', models.ManyToManyField(to='comentarios.Comentario')),
                ('producto', models.ManyToManyField(to='productos.Producto')),
                ('tag', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
