# Generated by Django 2.1 on 2019-01-10 22:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=None)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('email', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('sitio_web', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('telefono', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=None)),
                ('redes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('direccion', models.CharField(max_length=100)),
                ('hora_abierto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00}', max_length=100), size=None)),
                ('hora_cerrado', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00}', max_length=100), size=None)),
                ('dias_servicio', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo}', max_length=100), size=None)),
                ('latitud', models.DecimalField(decimal_places=15, max_digits=30)),
                ('longitud', models.DecimalField(decimal_places=15, max_digits=30)),
                ('fecha_creacion', models.DateField()),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria')),
                ('comentario', models.ManyToManyField(blank=True, to='comentarios.Comentario')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
                ('tag', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
