# Generated by Django 2.1 on 2018-12-17 03:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='dias_servicio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo}', max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='hora_abierto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00, 06:00:00}', max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='hora_cerrado',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00, 22:00:00}', max_length=100), size=None),
        ),
    ]
