# Generated by Django 2.1 on 2018-10-02 18:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('comentarios', '0002_auto_20181002_1206'),
        ('categorias', '0001_initial'),
        ('productos', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='categoria',
        ),
        migrations.AddField(
            model_name='lugar',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='comentario',
        ),
        migrations.AddField(
            model_name='lugar',
            name='comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comentarios.Comentario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='foto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), size=None),
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='producto',
        ),
        migrations.AddField(
            model_name='lugar',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='redes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='sitio_web',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='tag',
        ),
        migrations.AddField(
            model_name='lugar',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='telefono',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), size=None),
        ),
    ]
