# Generated by Django 2.1 on 2019-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20190319_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=20),
        ),
    ]
