# Generated by Django 2.1 on 2018-10-02 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_lugar_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
