# Generated by Django 2.1 on 2019-04-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_auto_20190330_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='calificacion',
            field=models.DecimalField(decimal_places=25, max_digits=30),
        ),
    ]
