# Generated by Django 2.1 on 2018-10-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('comentarios', '0002_auto_20181002_1206'),
        ('tags', '0001_initial'),
        ('lugares', '0004_lugar_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='comentario',
        ),
        migrations.AddField(
            model_name='lugar',
            name='comentario',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='producto',
        ),
        migrations.AddField(
            model_name='lugar',
            name='producto',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='tag',
        ),
        migrations.AddField(
            model_name='lugar',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
