# Generated by Django 2.1 on 2019-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0004_auto_20190412_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
