# Generated by Django 2.1 on 2019-07-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190204_2158'),
        ('lugares', '0006_recomendacionlugares'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionlugares',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
