# Generated by Django 2.1 on 2019-01-10 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=20)),
                ('foto', models.CharField(max_length=100)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugar')),
            ],
        ),
    ]
