# Generated by Django 2.1 on 2018-09-21 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_suscripcion', models.DateTimeField()),
                ('notificaciones', models.BooleanField(default=True)),
                ('lugar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
    ]
