# Generated by Django 2.1 on 2018-10-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='hora_suscripcion',
            field=models.TimeField(default='20:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_suscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugar'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
