# Generated by Django 2.1 on 2019-03-20 03:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='nit',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='dias_servicio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{Lunes, Martes, Miercoles, Jueves, Viernes, Sabado, Domingo}', max_length=100), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hora_abierto',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{N, N, N, N, N, N, N}', max_length=100), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hora_cerrado',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{N, N, N, N, N, N, N}', max_length=100), default='{}', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
