# Generated by Django 2.1 on 2019-06-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_auto_20190319_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='latitud',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='longitud',
            field=models.DecimalField(decimal_places=20, max_digits=40),
        ),
    ]
